/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content_admin;

import com.sun.glass.events.KeyEvent;
import inc.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import views.utama_admin;
/**
 *
 * @author fajarsubeki
 */
public class data_kasir extends javax.swing.JFrame {

    Connection conn = config.Conn();
    Statement st;
    ResultSet rs;
    PreparedStatement pr;
    
    private void tampil(){
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        model.addColumn("NO");;
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        model.addColumn("Status");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Akses");
 
        try{
            String sql = "SELECT * FROM tb_kasir";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            int no = 0;
            while(rs.next()){
                no++;
                model.addRow(new Object[]{
                    no, rs.getString("id_kasir"), rs.getString("nama"), rs.getString("alamat"), rs.getString("telepon"), rs.getString("status"), rs.getString("username"), rs.getString("password"), rs.getString("akses")
                });
            }
            tdata.setModel(model);
        } catch ( Exception e) {    
            System.out.println(e.getMessage());
        }
    }
    
    public void kode(){
        try {
            String sql = "SELECT * FROM tb_kasir ORDER BY id_kasir DESC";
            pr = conn.prepareStatement(sql);
            rs = pr.executeQuery();
            if (rs.next()) {
                String kode_otomatis = rs.getString("id_kasir").substring(1);
                String an = ""+(Integer.parseInt(kode_otomatis)+1);
                String nol = "";
                if (an.length() == 1) {
                    nol = "0000";
                }else if(an.length() == 2){
                    nol = "000";
                }else if(an.length() == 3){
                    nol = "00";
                }else if(an.length() == 4){
                    nol = "0";
                }else if(an.length() == 5){
                    nol = "";
                }
                tid.setText("D"+nol+an);
            }else{
                tid.setText("D00001");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * Creates new form data_kasir
     */
    public data_kasir() {
        initComponents();
        kode();
        tid.setEnabled(false);
        bubah.setEnabled(false);
        bhapus.setEnabled(false);
    }
    
    public void kosong(){
        tnama.setText("");
        talamat.setText("");
        thp1.setText("");
        tusername.setText("");
        tpassword.setText("");
        cbstatus.setSelectedItem("Pilih Status");
        cbakses.setSelectedItem("Pilih Akses");
        kode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        tnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbakses = new javax.swing.JComboBox<>();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        brefresh = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tdata = new javax.swing.JTable();
        thp1 = new javax.swing.JTextField();
        tpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA KASIR");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");

        tid.setEditable(false);
        tid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tidFocusGained(evt);
            }
        });
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        tid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tidKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telepon");

        talamat.setColumns(20);
        talamat.setRows(5);
        jScrollPane1.setViewportView(talamat);

        tnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnamaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status");

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        tusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tusernameKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Akses");

        cbakses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kasir", "admin" }));

        bsimpan.setBackground(new java.awt.Color(255, 255, 255));
        bsimpan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(0, 153, 153));
        bsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ok_25px.png"))); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(255, 255, 255));
        bhapus.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(0, 153, 153));
        bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_25px.png"))); // NOI18N
        bhapus.setText("Hapus");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        brefresh.setBackground(new java.awt.Color(255, 255, 255));
        brefresh.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        brefresh.setForeground(new java.awt.Color(0, 153, 153));
        brefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh_25px.png"))); // NOI18N
        brefresh.setText("Refresh");
        brefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brefreshActionPerformed(evt);
            }
        });

        bubah.setBackground(new java.awt.Color(255, 255, 255));
        bubah.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        bubah.setForeground(new java.awt.Color(0, 153, 153));
        bubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit_25px.png"))); // NOI18N
        bubah.setText("Ubah");
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bubahMouseClicked(evt);
            }
        });
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search_48px.png"))); // NOI18N
        jLabel9.setText("Pencarian");

        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });

        tdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "ID", "Nama", "Alamat", "Telepon", "Status", "Username", "Password", "Akses"
            }
        ));
        tdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdataMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tdataMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tdata);

        thp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thp1ActionPerformed(evt);
            }
        });
        thp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                thp1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tusername)
                                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thp1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbakses, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tnama)
                                    .addComponent(tpassword)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(brefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 346, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(434, 434, 434))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thp1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbakses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tidFocusGained
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_tidFocusGained

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
        talamat.requestFocus();
    }//GEN-LAST:event_tidActionPerformed

    private void tidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tidKeyTyped

    private void tnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnamaKeyTyped
        // TODO add your handling code here:
        char a= evt.getKeyChar();
        if (tnama.getText().length() > 30){
            JOptionPane.showMessageDialog(null, "Terlalu Panjang Memasukan Nama", "Peringatan", JOptionPane.WARNING_MESSAGE);evt.consume();;
        } else if ((Character.isDigit(a))) {
            JOptionPane.showMessageDialog(null,"Maaf Kolom Harus Diisi Dengan Huruf", "Peringatan", JOptionPane.WARNING_MESSAGE);evt.consume();
        }
    }//GEN-LAST:event_tnamaKeyTyped

    private void tusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tusernameKeyTyped
        // TODO add your handling code here:
        if (tusername.getText().length() > 15){
            JOptionPane.showMessageDialog(null, "Maksimal yang dimasukan Hanya 15 Karakter", "Peringatan", JOptionPane.WARNING_MESSAGE);evt.consume();;
        }
    }//GEN-LAST:event_tusernameKeyTyped

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        if(tnama.getText().equals("") || talamat.getText().equals("") || thp1.getText().equals("") || cbstatus.getSelectedItem().toString().equals("") || tusername.getText().equals("") || tpassword.getText().equals("") || cbakses.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Masih ada data yang masih kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            try{
                String sql = "INSERT INTO tb_kasir VALUES ('"+tid.getText()+"', '"+tnama.getText()+"', '"+talamat.getText()+"', '"+thp1.getText()+"', '"+cbstatus.getSelectedItem().toString()+"', '"+ tusername.getText()+"', '"+ tpassword.getText()+"', '"+cbakses.getSelectedItem().toString()+"')";
                st = conn.createStatement();
                st.executeUpdate(sql);

                kosong();
                tampil();
                kode();
                JOptionPane.showMessageDialog(null, "Berhasil Tersimpan");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        if(tnama.getText().equals("") || talamat.getText().equals("") || thp1.getText().equals("") || cbstatus.getSelectedItem().toString().equals("") || tusername.getText().equals("") || tpassword.getText().equals("") || cbakses.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null,"Data masih kosong","Peringatan",JOptionPane.WARNING_MESSAGE);
        } else {
            try{
                int jawab;
                if((jawab = JOptionPane.showConfirmDialog(null, "Ingin Menghapus ?", "Konrimasi", JOptionPane.YES_NO_OPTION)) == 0){
                    String sql = "DELETE FROM  tb_kasir WHERE id_kasir = '"+tid.getText()+"'";
                    st = conn.createStatement();
                    st.executeUpdate(sql);
                    kosong();
                    tampil();
                    kode();
                    JOptionPane.showMessageDialog(null, "Berhasil Di Hapus");
                }
            }
            catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void brefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brefreshActionPerformed
        // TODO add your handling code here:
        bubah.setEnabled(false);
        bhapus.setEnabled(false);
        bsimpan.setEnabled(true);
        kosong();
    }//GEN-LAST:event_brefreshActionPerformed

    private void bubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bubahMouseClicked

    }//GEN-LAST:event_bubahMouseClicked

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        if(tnama.getText().equals("") || talamat.getText().equals("") || thp1.getText().equals("") || cbstatus.getSelectedItem().toString().equals("") || tusername.getText().equals("") || tpassword.getText().equals("") || cbakses.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null,"Data masih kosong","Peringatan",JOptionPane.WARNING_MESSAGE);
        } else {
            try{
                String sql = "UPDATE tb_kasir SET nama = '"+tnama.getText()+"', alamat = '"+talamat.getText()+"', telepon = '"+thp1.getText()+"', status = '"+cbstatus.getSelectedItem().toString()+"', username = '"+tusername.getText()+"', password = '"+tpassword.getText()+"', akses = '"+cbakses.getSelectedItem().toString()+"' WHERE id_kasir = '"+tid.getText()+"'";
                st = conn.createStatement();
                st.executeUpdate(sql);
                kosong();
                tampil();
                kode();
                bubah.setEnabled(false);
                bhapus.setEnabled(false);
                bsimpan.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Berhasil Di Update");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_bubahActionPerformed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        model.addColumn("Status");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Akses");
        try{
            String sql = "SELECT * FROM tb_kasir WHERE id_kasir LIKE '%"+tcari.getText()+"%' OR nama LIKE '%"+tcari.getText()+"%' OR alamat LIKE '%"+tcari.getText()+"%' OR telepon LIKE '%"+tcari.getText()+"%' OR status LIKE '%"+tcari.getText()+"%' OR username LIKE '%"+tcari.getText()+"%' OR password LIKE '%"+tcari.getText()+"%' OR akses LIKE '%"+tcari.getText()+"%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            int no = 0;
            while(rs.next()){
                no++;
                model.addRow(new Object[]{
                    no, rs.getString("id_kasir"), rs.getString("nama"), rs.getString("alamat"), rs.getString("telepon"), rs.getString("status"), rs.getString("username"), rs.getString("password"), rs.getString("akses")
                });
            }
            tdata.setModel(model);
        } catch ( Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tcariKeyPressed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariKeyReleased

    private void tdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdataMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tdataMouseClicked

    private void thp1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thp1KeyTyped
        // TODO add your handling code here:
        char a= evt.getKeyChar();
        if (! (Character.isDigit(a) || (a==KeyEvent.VK_BACKSPACE) || (a==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null,"Maaf Kolom Harus Diisi Dengan Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);evt.consume();
        } else if (thp1.getText().length() > 12){
            JOptionPane.showMessageDialog(null, "Maksimal yang dimasukan Hanya 12 Karakter", "Peringatan", JOptionPane.WARNING_MESSAGE);evt.consume();;
        }
    }//GEN-LAST:event_thp1KeyTyped

    private void thp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thp1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void tdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdataMousePressed
        // TODO add your handling code here:
        try {
            int bar = tdata.getSelectedRow();
            String a = tdata.getValueAt(bar, 0).toString();
            String b = tdata.getValueAt(bar, 1).toString();
            String c = tdata.getValueAt(bar, 2).toString();
            String d = tdata.getValueAt(bar, 3).toString();
            String e = tdata.getValueAt(bar, 4).toString();
            String f = tdata.getValueAt(bar, 5).toString();
            String g = tdata.getValueAt(bar, 6).toString();
            String h = tdata.getValueAt(bar, 7).toString();
            String i = tdata.getValueAt(bar, 8).toString();
            
            tid.setText(b);
            tnama.setText(c);
            talamat.setText(d);
            thp1.setText(e);
            cbstatus.setSelectedItem(f);
            tusername.setText(g);
            tpassword.setText(h);
            cbakses.setSelectedItem(i);
        } catch (Exception e) {
            e.printStackTrace();
        }
        bubah.setEnabled(true);
        bhapus.setEnabled(true);
        bsimpan.setEnabled(false);
    }//GEN-LAST:event_tdataMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton brefresh;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbakses;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTextField tcari;
    private javax.swing.JTable tdata;
    private javax.swing.JTextField thp1;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tnama;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
